# 第3章 K邻近法

## K邻近算法
三个基本要素：
- 距离度量： 欧氏距离、曼哈顿距离等等
- k值：一般取小，交叉验证来选择更适合的
- 分类决策规则：往往选择多数表决

$L_p$距离定义
$$L_p(xi, xj) = (\sum_{l=1}^n\left |x_i^{(l)} - x_j^{(l)}\right |^p)^\frac{1}{p}$$
$p \geq 1$

In [108]:
import numpy as np

p=2,欧式距离(Euclidean distance)$$L_2(xi, xj) = (\sum_{l=1}^n\left |x_i^{(l)} - x_j^{(l)}\right |^2)^\frac{1}{2}$$

In [3]:
# 欧几里得距离
def euclideanDistance(x1, x2):
    return np.sqrt(np.sum(np.square(x1-x2)))

p=1,曼哈顿距离(Manhattan distance)$$L_1(xi, xj) = \sum_{l=1}^n\left |x_i^{(l)} - x_j^{(l)}\right |$$

In [4]:
def manhattanDistance(x1, x2):
    return np.sum(np.abs(x1-x2))

In [109]:
def loadData():
    import tensorflow as tf
    mnist = tf.keras.datasets.mnist
    (X_train, y_train),(X_test, y_test) = mnist.load_data()
    X_train[X_train >= 127] = 1
    X_train[X_train < 127] = 0
    X_test[X_test >= 127] = 1
    X_test[X_test < 127] = 0
    # X_train, X_test = X_train / 255.0, X_test / 255.0 # 标准化
    X_train = X_train.reshape(X_train.shape[0], X_train.size // X_train.shape[0])
    X_test = X_test.reshape(X_test.shape[0], X_test.size // X_test.shape[0])
    return X_train, X_test, y_train, y_test

In [117]:
def kNearestNeighbor(X_train, y_train, vec, k=1, kind='eu'):
    """
    Parameters:
        X_train: 训练数据集
        y_train: 训练标签集
        vec: 用于预测的数据
        k: K值
    Returns:
        预测标签
    """
    trainSize = X_train.shape[0]
    cls_cnt = {}  # 用来判断测试数据属于哪个分类
    if kind == 'eu':
        # 欧式距离
        dist = np.apply_along_axis(euclideanDistance, 1, X_train, vec)  # 这个函数帮助我们再每行应用计算距离 
    if kind == 'ma':
        # 曼哈顿距离
        dist = np.apply_along_axis(manhattanDistance, 1, X_train, vec)  # 这个函数帮助我们再每行应用计算距离
        
    for el in dist.argsort()[:k]:
        cls_cnt[y_train[el]] = cls_cnt[y_train[el]] + 1 if y_train[el] in cls_cnt else 1
    return max(cls_cnt)

In [114]:
err = 0
testSize = 20
for i in range(testSize):
    print('Testing the {} data'.format(i))
    test_vec = X_test[i]
    pred = kNearestNeighbor(X_train, y_train, test_vec, 3, kind='eu')
    if pred != y_test[i]:
        err += 1
        print(err)
acc = 1 - err / testSize
print(acc)

Testing the 0 data
Testing the 1 data
Testing the 2 data
Testing the 3 data
Testing the 4 data
Testing the 5 data
Testing the 6 data
Testing the 7 data
Testing the 8 data
Testing the 9 data
Testing the 10 data
Testing the 11 data
Testing the 12 data
Testing the 13 data
Testing the 14 data
Testing the 15 data
Testing the 16 data
Testing the 17 data
Testing the 18 data
Testing the 19 data
1.0


In [94]:
X_train, X_test, y_train, y_test = loadData()

In [107]:
X_test.shape

(10000, 784)

In [118]:
test_vec = X_test[0]
%prun kNearestNeighbor(X_train, y_train, test_vec, 5, kind='eu')

In [88]:
dist = np.apply_along_axis(euclideanDistance, 1, X_train, test_vec)

In [89]:
dist.argsort()

array([53843, 38620, 16186, ..., 25321, 59439, 41358])

array([ 9.39527723, 10.39462864,  9.4404245 , ...,  9.46745777,
        9.53388582,  9.22310757])

In [70]:
for el in dist

array([ 9.39527723, 10.39462864])